# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapi', '0002_auto_20170714_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='test_id',
        ),
    ]
